spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/v1/auth/**,/api/v1/users/**,/api/v1/users
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/products,/api/v1/products/**
            - id: cart-service
              uri: lb://CART-SERVICE
              predicates:
                - Path=/api/v1/carts/**
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/v1/customers,/api/v1/customers/**
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/v1/inventory,/api/v1/inventory/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders,/api/v1/orders/**
            - id: notifications-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/api/v1/notifications,/api/v1/notifications/**
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/v1/payments,/api/v1/payments/**
            - id: review-service
              uri: lb://REVIEW-SERVICE
              predicates:
                - Path=/api/v1/reviews,/api/v1/reviews/**

server:
  port: 9000